FROM node:lts-slim
WORKDIR /
COPY . .
RUN apk add --no-cache --virtual .gyp \
		python \
		make \
		g++ \
	&& npm install \
	&& apk del .gyp
RUN npm run build
WORKDIR /
EXPOSE 3000
CMD ["npm", "run", "start"]